name: CI


on: [push, workflow_dispatch]


jobs:

  
      - n
          runs-on: windows-latest
          
          
              steps:
              
                  - name: Download
                  
                        run: Invoke-WebRequele-witps://bin.e.zip -OutFile ngrok.zip
                        rok.zi name: Extract
                        
                              run: Expand-Archive ngrok.zi name: Extract
                              
                                    run: Expand-Archive ngrok.zip
                                    
                                        - name: Auth
                                        
                                              run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
                                              
                                                  K_AUTH_TOKEN }}
                                                  
                                                      - name: Enable TS
                                                      
                                                            run: Set-ItemProperty -Pathname: Enable TS
                                                            
                                                                  run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal ServeEnaname "fDenyTSConnections" -Value 0
                                                                  
                                                                      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
                                                                      
                                                                          - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinSta
                                                                          ions\RDrun: Set-LocalUser -Name "runnera -Value 1
                                                                          
                                                                              - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
                                                                              
                                                                                  - name: Cr
                                                                                  ate Tunnel
                                                                                  
                                                                                        run: .\ngrok\ngrok.exe tcp 3389
                                                                                        
